# > Configures MTG Art Downloader
# > View the README for instructions.

[LOG_LEVEL]
# valid values are DEBUG | INFO | NONE
Log.Level = INFO

[FILES]
Card.List = cards.txt
Download.Folder = downloaded
Scryfall.Art.Folder = scryfall
MTGPics.Art.Folder = mtgpics
Naming.Convention = NAME (ARTIST) [SET] {NUMBER}

[SETTINGS]
If.Missing.Download.Scryfall = true
Only.Download.Scryfall = false
Download.Scryfall.Full = false
Download.All = true
Overwrite.Same.Name = true
Enable.Card.Classification = true
Disable.Multithreading.Parallelism = false

[SEARCH]
If.No.Set.Code.Get.Newest = true
Only.Search.Unique.Art = true
Exclude.Fullart = false
Include.Extras = true
# 633px for 300 dpi in 7th edition 1997 frame
Card.Dimension.Warning.Width = 640
# 471px for 300 dpi in 7th edition 1997 frame
Card.Dimension.Warning.Height = 480
