[tool.poetry]
name = "MTG-Art-Downloader"
version = "v1.5.1"
description = "Mass download MTG card arts using MTG Pics with Scryfall as a backup source."
authors = ["MrTeferi <freethoughtleft@gmail.com>"]
license = "GNU General Public License v3.0"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.13,<3.15"
black = "^25.12.0"
bs4 = "^0.0.2"
pyyaml = "^6.0.3"
colorama = "^0.4.6"
contextlib3 = "^3.10.0"
mypy = "^1.19.0"
pre-commit = "^4.5.1"
pyclean = "^3.4.0"
pytest = "^9.0.2"
requests = "^2.32.5"
Unidecode = "^1.4.0"
urllib3 = "^2.6.2"
pyinstaller = "^6.17.0"
hjson = "^3.1.0"
pathvalidate = "^3.3.1"
ratelimit = "^2.2.1"
backoff = "^2.2.1"
pillow = "^12.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "bs4",
    "colorama",
    "PIL"
]
ignore_missing_imports = true