# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests and Type Checks

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read

jobs:
  test:
    #-----------------------------------------------
    # - Pre-Commit Check, MyPy Check, PyTest Cases -
    #-----------------------------------------------
    name: Test on Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.13', '3.14']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v6.1.0
      # https://github.com/actions/setup-python
      with:
        python-version: ${{ matrix.python_version }}
    #-----------------------------------------------
    #  -----  install Poetry and Dependencies  -----
    #-----------------------------------------------
    - name: Install Poetry & Dependencies
      run: |
        python -m pip install -U pip poetry
        poetry install
    - name: Precommit, MyPy check, PyTest check
      run: |
        poetry run pre-commit run --all-files
        poetry run mypy main.py --ignore-missing-imports --exclude requests
        poetry run mypy build.py --ignore-missing-imports --exclude requests
        poetry run mypy src --ignore-missing-imports --exclude requests
        poetry run pytest src/tests.py
        poetry run pytest src/test_card_classifier.py
